from __future__ import annotations

import json
import urllib.parse
from typing import Any


def schema_blank_payload(schema: dict[str, Any]) -> dict[str, Any]:
    properties = schema.get("properties", {}) if isinstance(schema.get("properties"), dict) else {}
    result: dict[str, Any] = {}
    for key, value in properties.items():
        result[str(key)] = blank_value_from_schema(value if isinstance(value, dict) else {})
    return result


def extract_request_schema(request_body: object) -> dict[str, Any]:
    if not isinstance(request_body, dict):
        return {}
    content = request_body.get("content")
    if not isinstance(content, dict):
        return {}
    app_json = content.get("application/json")
    if not isinstance(app_json, dict):
        return {}
    schema = app_json.get("schema")
    return schema if isinstance(schema, dict) else {}


def blank_value_from_schema(schema: dict[str, Any]) -> Any:
    schema_type = schema.get("type")
    if schema_type == "object" or isinstance(schema.get("properties"), dict):
        return None
    if schema_type == "array":
        return []
    return None


def deep_merge_payload(base: Any, override: Any) -> Any:
    if isinstance(base, dict) and isinstance(override, dict):
        merged = dict(base)
        for key, value in override.items():
            merged[key] = deep_merge_payload(merged.get(key), value) if key in merged else value
        return merged
    return override if override is not None else base


def derive_base_url(current_base_url: str, replacement_path: str) -> str:
    parsed = urllib.parse.urlparse(current_base_url)
    return urllib.parse.urlunparse((parsed.scheme, parsed.netloc, replacement_path, "", "", ""))


def build_generated_test_file(generated_tests: list[dict[str, Any]]) -> str:
    cases_json = json.dumps(generated_tests, ensure_ascii=False, indent=2)
    return "\n".join(
        [
            "from __future__ import annotations",
            "",
            "import json",
            "import os",
            "import urllib.error",
            "import urllib.request",
            "",
            "import pytest",
            "",
            "try:",
            "    import allure",
            "except ImportError:  # pragma: no cover - generated tests still need to be importable without Allure.",
            "    class _NoopAttachmentType:",
            "        JSON = 'application/json'",
            "        TEXT = 'text/plain'",
            "",
            "    class _NoopDynamic:",
            "        def epic(self, *_args, **_kwargs) -> None:",
            "            return None",
            "",
            "        def feature(self, *_args, **_kwargs) -> None:",
            "            return None",
            "",
            "        def story(self, *_args, **_kwargs) -> None:",
            "            return None",
            "",
            "        def title(self, *_args, **_kwargs) -> None:",
            "            return None",
            "",
            "    class _NoopStep:",
            "        def __enter__(self):",
            "            return self",
            "",
            "        def __exit__(self, *_args):",
            "            return False",
            "",
            "    class _NoopAllure:",
            "        attachment_type = _NoopAttachmentType()",
            "        dynamic = _NoopDynamic()",
            "",
            "        def step(self, *_args, **_kwargs):",
            "            return _NoopStep()",
            "",
            "        def attach(self, *_args, **_kwargs) -> None:",
            "            return None",
            "",
            "    allure = _NoopAllure()",
            "",
            "BASE_URL = os.getenv('API_BASE_URL')",
            "FRONT_USERNAME = os.getenv('FRONT_USERNAME')",
            "FRONT_PASSWORD = os.getenv('FRONT_PASSWORD')",
            "FRONT_LOGIN_PATH = os.getenv('FRONT_LOGIN_PATH', '/api/front/auth/login')",
            "FRONT_TOKEN_JSON_PATH = os.getenv('FRONT_TOKEN_JSON_PATH', 'data.token')",
            "AUTH_HEADER_NAME = os.getenv('AUTH_HEADER_NAME', 'Authorization')",
            "AUTH_SCHEME = os.getenv('AUTH_SCHEME', 'Bearer')",
            "FRONT_LOGIN_BODY_TEMPLATE = os.getenv('FRONT_LOGIN_BODY_TEMPLATE')",
            "FRONT_LOGIN_HEADERS_JSON = os.getenv('FRONT_LOGIN_HEADERS_JSON')",
            "FRONT_LOGIN_METHOD = os.getenv('FRONT_LOGIN_METHOD', 'POST')",
            "FRONT_SYS_TYPE = os.getenv('FRONT_SYS_TYPE')",
            "LOGIN_SUCCESS_MARKER = os.getenv('LOGIN_SUCCESS_MARKER')",
            "SUCCESS_RESPONSE_CODE = os.getenv('SUCCESS_RESPONSE_CODE', '00000')",
            "CONTEXT: dict[str, object] = {}",
            "pytestmark = pytest.mark.skipif(",
            "    not BASE_URL,",
            "    reason='Set API_BASE_URL to execute generated API tests.',",
            ")",
            "",
            f"CASES = json.loads({cases_json!r})",
            "",
            "def _json_attachment(name: str, value: object) -> None:",
            "    allure.attach(",
            "        json.dumps(value, ensure_ascii=False, indent=2),",
            "        name=name,",
            "        attachment_type=allure.attachment_type.JSON,",
            "    )",
            "",
            "def _join_url(base_url: str, path: str) -> str:",
            "    if path.startswith('http://') or path.startswith('https://'):",
            "        return path",
            "    return f\"{base_url.rstrip('/')}\" + '/' + path.lstrip('/')",
            "",
            "def _parse_json_object(raw: str | None) -> dict[str, object]:",
            "    if not raw or raw in {'4', 'null', 'None'}:",
            "        return {}",
            "    data = json.loads(raw)",
            "    return data if isinstance(data, dict) else {}",
            "",
            "def _build_login_payload() -> dict[str, object]:",
            "    if FRONT_LOGIN_BODY_TEMPLATE and FRONT_LOGIN_BODY_TEMPLATE not in {'4', 'null', 'None'}:",
            "        rendered = FRONT_LOGIN_BODY_TEMPLATE",
            "        replacements = {",
            "            '${username}': FRONT_USERNAME or '',",
            "            '${password}': FRONT_PASSWORD or '',",
            "            '${sysType}': FRONT_SYS_TYPE or '',",
            "        }",
            "        for needle, value in replacements.items():",
            "            rendered = rendered.replace(needle, value)",
            "        payload = json.loads(rendered)",
            "        return payload if isinstance(payload, dict) else {}",
            "    payload: dict[str, object] = {'username': FRONT_USERNAME, 'password': FRONT_PASSWORD}",
            "    if FRONT_SYS_TYPE and FRONT_SYS_TYPE not in {'4', '不知道'}:",
            "        payload['sysType'] = FRONT_SYS_TYPE",
            "    return payload",
            "",
            "def _authorization_value(token: str) -> str:",
            "    if not AUTH_SCHEME or AUTH_SCHEME in {'无前缀', 'NONE', 'none'}:",
            "        return token",
            "    return f'{AUTH_SCHEME} {token}'.strip()",
            "",
            "def _extract_json_path(payload: dict[str, object], path: str) -> object:",
            "    current: object = payload",
            "    for part in path.split('.'):",
            "        if not isinstance(current, dict) or part not in current:",
            "            raise AssertionError(f'Missing token field: {path}')",
            "        current = current[part]",
            "    return current",
            "",
            "def _matches_success_marker(response_text: str, marker: str | None) -> bool:",
            "    if not marker or marker in {'4', 'null', 'None'}:",
            "        return True",
            "    if '=' in marker:",
            "        key, _, expected = marker.partition('=')",
            "        key = key.strip()",
            "        expected = expected.strip()",
            "        if not key:",
            "            return marker in response_text",
            "        try:",
            "            body = _json_body(response_text)",
            "            actual = _extract_json_path(body, key)",
            "        except AssertionError:",
            "            return False",
            "        return str(actual) == expected",
            "    return marker in response_text",
            "",
            "def _send_json(",
            "    method: str,",
            "    path: str,",
            "    payload_obj: object | None = None,",
            "    headers: dict[str, str] | None = None,",
            ") -> tuple[int, str]:",
            "    body = None if method == 'GET' else json.dumps(payload_obj or {}).encode('utf-8')",
            "    request = urllib.request.Request(",
            "        url=_join_url(BASE_URL or '', path),",
            "        data=body,",
            "        headers={'Content-Type': 'application/json', **(headers or {})},",
            "        method=method,",
            "    )",
            "    try:",
            "        with urllib.request.urlopen(request, timeout=10) as response:",
            "            return response.getcode(), response.read().decode('utf-8')",
            "    except urllib.error.HTTPError as exc:",
            "        return exc.code, exc.read().decode('utf-8')",
            "",
            "def _login_front_user() -> dict[str, str]:",
            "    if 'front_auth_headers' in CONTEXT:",
            "        return CONTEXT['front_auth_headers']  # type: ignore[return-value]",
            "    if not FRONT_USERNAME or not FRONT_PASSWORD:",
            "        pytest.skip('缺少 FRONT_USERNAME 或 FRONT_PASSWORD，无法执行需要登录态的接口用例。')",
            "    login_headers = {str(key): str(value) for key, value in _parse_json_object(FRONT_LOGIN_HEADERS_JSON).items()}",
            "    status_code, response_text = _send_json(",
            "        FRONT_LOGIN_METHOD,",
            "        FRONT_LOGIN_PATH,",
            "        _build_login_payload(),",
            "        headers=login_headers,",
            "    )",
            "    allure.attach(",
            "        response_text,",
            "        name='前台登录响应',",
            "        attachment_type=allure.attachment_type.JSON,",
            "    )",
            "    assert _matches_success_marker(response_text, LOGIN_SUCCESS_MARKER)",
            "    _assert_success_response(status_code, response_text)",
            "    token = str(_extract_json_path(json.loads(response_text), FRONT_TOKEN_JSON_PATH))",
            "    CONTEXT['front_auth_headers'] = {AUTH_HEADER_NAME: _authorization_value(token)}",
            "    _reset_cart_once(CONTEXT['front_auth_headers'])  # type: ignore[arg-type]",
            "    return CONTEXT['front_auth_headers']  # type: ignore[return-value]",
            "",
            "def _reset_cart_once(headers: dict[str, str]) -> None:",
            "    if CONTEXT.get('cart_reset_done'):",
            "        return",
            "    CONTEXT['cart_reset_done'] = True",
            "    status_code, response_text = _send_json('GET', '/api/front/cart/items', headers=headers)",
            "    if status_code != 200:",
            "        return",
            "    body = _json_body(response_text)",
            "    data = body.get('data', {})",
            "    items = data.get('items', []) if isinstance(data, dict) else []",
            "    ids = [int(item['id']) for item in items if isinstance(item, dict) and item.get('id') is not None]",
            "    if ids:",
            "        _send_json('DELETE', '/api/front/cart/items', {'ids': ids}, headers=headers)",
            "",
            "def _auth_headers(case: dict[str, object]) -> dict[str, str]:",
            "    if 401 in case.get('expected_status_codes', []):",
            "        return {}",
            "    return _login_front_user()",
            "",
            "def _json_body(response_text: str) -> dict[str, object]:",
            "    try:",
            "        body = json.loads(response_text)",
            "    except json.JSONDecodeError:",
            "        return {}",
            "    return body if isinstance(body, dict) else {}",
            "",
            "def _business_code(response_text: str) -> object:",
            "    return _json_body(response_text).get('code')",
            "",
            "def _assert_success_response(http_status_code: int, response_text: str) -> None:",
            "    assert http_status_code == 200",
            "    code = _business_code(response_text)",
            "    if code is None:",
            "        return",
            "    assert str(code) == SUCCESS_RESPONSE_CODE",
            "",
            "def _effective_status_code(http_status_code: int, response_text: str) -> int:",
            "    code = _business_code(response_text)",
            "    if isinstance(code, int):",
            "        return code",
            "    if isinstance(code, str):",
            "        if code == SUCCESS_RESPONSE_CODE:",
            "            return http_status_code",
            "        if 200 <= http_status_code < 300:",
            "            return 599",
            "    return http_status_code",
            "",
            "def _front_get(path: str) -> dict[str, object]:",
            "    status_code, response_text = _send_json('GET', path, headers=_login_front_user())",
            "    _assert_success_response(status_code, response_text)",
            "    return _json_body(response_text)",
            "",
            "def _valid_pet_ids() -> list[int]:",
            "    if 'valid_pet_ids' in CONTEXT:",
            "        return CONTEXT['valid_pet_ids']  # type: ignore[return-value]",
            "    body = _front_get('/api/front/pets')",
            "    records = body.get('data', {}).get('records', []) if isinstance(body.get('data'), dict) else []",
            "    ids = [",
            "        int(item['id'])",
            "        for item in records",
            "        if isinstance(item, dict)",
            "        and item.get('id') is not None",
            "        and item.get('pet_status') == 1",
            "        and int(item.get('stock_quantity') or 0) > 0",
            "    ]",
            "    if not ids:",
            "        pytest.skip('缺少上架且库存大于 0 的宠物测试数据。')",
            "    CONTEXT['valid_pet_ids'] = ids",
            "    return ids",
            "",
            "def _ensure_cart_items(count: int = 1) -> list[int]:",
            "    for pet_id in _valid_pet_ids()[:count]:",
            "        _send_json(",
            "            'POST',",
            "            '/api/front/cart/items',",
            "            {'pet_id': pet_id, 'quantity': 1},",
            "            headers=_login_front_user(),",
            "        )",
            "    body = _front_get('/api/front/cart/items')",
            "    data = body.get('data', {})",
            "    items = data.get('items', []) if isinstance(data, dict) else []",
            "    ids = [int(item['id']) for item in items if isinstance(item, dict) and item.get('id') is not None]",
            "    if len(ids) < count:",
            "        pytest.skip(f'购物车测试数据不足，需要 {count} 条，当前 {len(ids)} 条。')",
            "    return ids[:count]",
            "",
            "def _resolve_placeholder(value: str) -> object:",
            "    if value == '${valid_pet_id}':",
            "        return _valid_pet_ids()[0]",
            "    if value == '${cart_item_id}' or value == '${cart_item_id_1}':",
            "        return _ensure_cart_items(1)[0]",
            "    if value == '${cart_item_id_2}':",
            "        return _ensure_cart_items(2)[1]",
            "    return value",
            "",
            "def _resolve_value(value: object) -> object:",
            "    if isinstance(value, str):",
            "        return _resolve_placeholder(value)",
            "    if isinstance(value, list):",
            "        return [_resolve_value(item) for item in value]",
            "    if isinstance(value, dict):",
            "        return {key: _resolve_value(item) for key, item in value.items()}",
            "    return value",
            "",
            "def _resolve_path(path: str) -> str:",
            "    if '{id}' in path:",
            "        path = path.replace('{id}', str(_ensure_cart_items(1)[0]))",
            "    return path",
            "",
            "def _case_headers(case: dict[str, object]) -> dict[str, str]:",
            "    headers: dict[str, str] = {}",
            "    for item in case.get('headers', []):",
            "        if not isinstance(item, dict):",
            "            continue",
            "        name = item.get('name')",
            "        example = item.get('example')",
            "        lowered = str(name).lower() if name else ''",
            "        if lowered in {'currentuser', 'authorization'}:",
            "            continue",
            "        if name and example not in {None, '', '4'}:",
            "            headers[str(name)] = str(example)",
            "    return headers",
            "",
            "def _extract_request_schema(request_body: object) -> dict[str, object]:",
            "    if not isinstance(request_body, dict):",
            "        return {}",
            "    content = request_body.get('content')",
            "    if not isinstance(content, dict):",
            "        return {}",
            "    app_json = content.get('application/json')",
            "    if not isinstance(app_json, dict):",
            "        return {}",
            "    schema = app_json.get('schema')",
            "    return schema if isinstance(schema, dict) else {}",
            "",
            "def _sample_string(field_name: str, schema: dict[str, object]) -> str:",
            "    if isinstance(schema.get('default'), str):",
            "        return str(schema['default'])",
            "    if isinstance(schema.get('example'), str):",
            "        return str(schema['example'])",
            "    lowered = field_name.lower()",
            "    if 'datetime' in lowered or ('time' in lowered and 'date' in lowered):",
            "        return '2099-12-31 10:00:00'",
            "    if 'date' in lowered:",
            "        return '2099-12-31'",
            "    if 'time' in lowered:",
            "        return '10:00:00'",
            "    if lowered.endswith('id') or lowered.endswith('name'):",
            "        return f'auto_{field_name}'",
            "    return f'auto_{field_name or \"value\"}'",
            "",
            "def _sample_scalar_value(field_name: str, schema: dict[str, object]) -> object:",
            "    if 'default' in schema:",
            "        return schema['default']",
            "    if 'example' in schema:",
            "        return schema['example']",
            "    enum_values = schema.get('enum')",
            "    if isinstance(enum_values, list) and enum_values:",
            "        return enum_values[0]",
            "    schema_type = schema.get('type')",
            "    if schema_type == 'boolean':",
            "        return False",
            "    if schema_type == 'integer':",
            "        return 1",
            "    if schema_type == 'number':",
            "        return 1",
            "    if schema_type == 'null':",
            "        return None",
            "    return _sample_string(field_name, schema)",
            "",
            "def _field_has_guidance(schema: object) -> bool:",
            "    return isinstance(schema, dict) and any(key in schema for key in ('default', 'example', 'enum'))",
            "",
            "def _should_autofill_field(field_name: str, schema: object, *, required: bool, seeded: bool) -> bool:",
            "    if required or seeded or _field_has_guidance(schema):",
            "        return True",
            "    lowered = field_name.lower()",
            "    blocked_fields = {",
            "        'id', 'userid', 'deptid', 'tenantid', 'systemid', 'pagenum', 'pagesize',",
            "        'welcomeconfigid', 'defaultmsgid', 'moduleid', 'modulerelationid',",
            "        'msginfoid', 'createsource', 'updatesource', 'pointer', 'sort'",
            "    }",
            "    if lowered in blocked_fields:",
            "        return False",
            "    if lowered.endswith('id') and lowered not in {'categoryid', 'corpid', 'userid'}:",
            "        return False",
            "    preferred_fields = {",
            "        'name', 'state', 'categoryid', 'effectivetype', 'shunttype',",
            "        'skipverify', 'nextautoenabletime', 'status', 'corpid', 'userid',",
            "        'alltimeusers', 'splittimeusers'",
            "    }",
            "    return lowered in preferred_fields",
            "",
            "def _schema_example_value(schema: object, field_name: str = '', seed: object = None) -> object:",
            "    if not isinstance(schema, dict):",
            "        return {}",
            "    schema_type = schema.get('type')",
            "    if schema_type == 'object' or isinstance(schema.get('properties'), dict):",
            "        result: dict[str, object] = {}",
            "        properties = schema.get('properties', {})",
            "        required_fields = set(str(item) for item in schema.get('required', []) if isinstance(item, str))",
            "        seed_map = seed if isinstance(seed, dict) else {}",
            "        if isinstance(properties, dict):",
            "            for key, value in properties.items():",
            "                if not isinstance(value, dict):",
            "                    continue",
            "                key_str = str(key)",
            "                if not _should_autofill_field(",
            "                    key_str,",
            "                    value,",
            "                    required=key_str in required_fields,",
            "                    seeded=isinstance(seed_map, dict) and key_str in seed_map,",
            "                ):",
            "                    continue",
            "                child_seed = seed_map.get(key_str) if isinstance(seed_map, dict) else None",
            "                result[key_str] = _schema_example_value(value, key_str, child_seed)",
            "        return result",
            "    if schema_type == 'array':",
            "        items = schema.get('items')",
            "        if isinstance(items, dict):",
            "            child_seed = seed[0] if isinstance(seed, list) and seed else None",
            "            return [_schema_example_value(items, field_name, child_seed)]",
            "        return []",
            "    return _sample_scalar_value(field_name, schema)",
            "",
            "def _deep_merge(base: object, override: object) -> object:",
            "    if isinstance(base, dict) and isinstance(override, dict):",
            "        merged = dict(base)",
            "        for key, value in override.items():",
            "            merged[key] = _deep_merge(merged.get(key), value) if key in merged else value",
            "        return merged",
            "    return override",
            "",
            "def _build_case_payload(case: dict[str, object]) -> object:",
            "    payload_obj = _resolve_value(case.get('payload', {}))",
            "    if case.get('payload_strategy') == 'raw_payload':",
            "        return payload_obj",
            "    schema = _extract_request_schema(case.get('request_body', {}))",
            "    if not schema:",
            "        return payload_obj",
            "    example_payload = _schema_example_value(schema, seed=payload_obj)",
            "    if isinstance(example_payload, dict) and isinstance(payload_obj, dict):",
            "        return _deep_merge(example_payload, payload_obj)",
            "    return payload_obj if payload_obj not in ({}, [], None) else example_payload",
            "",
            "def _request(case: dict[str, object]) -> tuple[int, str]:",
            "    method = str(case['method']).upper()",
            "    payload_obj = _build_case_payload(case)",
            "    payload = json.dumps(payload_obj).encode('utf-8')",
            "    resolved_path = _resolve_path(str(case['path']))",
            "    case_base_url = str(case.get('base_url') or BASE_URL or '')",
            "    url = _join_url(case_base_url, resolved_path)",
            "    headers = {'Content-Type': 'application/json', **_case_headers(case), **_auth_headers(case)}",
            "    _json_attachment(",
            "        '请求信息',",
            "        {'method': method, 'url': url, 'base_url': case_base_url, 'headers': headers, 'body': payload_obj},",
            "    )",
            "    request = urllib.request.Request(",
            "        url=url,",
            "        data=None if method == 'GET' else payload,",
            "        headers=headers,",
            "        method=method,",
            "    )",
            "    try:",
            "        with urllib.request.urlopen(request, timeout=10) as response:",
            "            status_code = response.getcode()",
            "            response_text = response.read().decode('utf-8')",
            "    except urllib.error.HTTPError as exc:",
            "        status_code = exc.code",
            "        response_text = exc.read().decode('utf-8')",
            "    _json_attachment('响应信息', {'status_code': status_code, 'body': response_text})",
            "    return status_code, response_text",
            "",
            "@pytest.mark.parametrize(",
            "    'case',",
            "    CASES,",
            "    ids=[str(case['automation_id']) for case in CASES],",
            ")",
            "def test_generated_api_case(case: dict[str, object]) -> None:",
            "    allure.dynamic.epic(str(case.get('epic', '宠物商店系统')))",
            "    allure.dynamic.feature(str(case.get('feature', '接口自动化')))",
            "    allure.dynamic.story(str(case.get('story', case.get('test_case_id', '自动化用例'))))",
            "    allure.dynamic.title(str(case.get('title', case.get('automation_id', '接口自动化用例'))))",
            "",
            "    with allure.step('前置条件：读取环境变量与测试用例数据'):",
            "        assert BASE_URL, '缺少 API_BASE_URL，无法执行接口自动化用例'",
            "        _json_attachment('测试用例元数据', case)",
            "        if case.get('skip_reason'):",
            "            pytest.skip(str(case['skip_reason']))",
            "",
            "    with allure.step('执行步骤：发送接口请求并采集响应'):",
            "        if case.get('test_case_id') == 'TC-CART-CHECKOUT-002':",
            "            pytest.skip('该用例需要稳定失效商品 fixture，当前先保留 Allure 设计和接口映射。')",
            "        if case.get('test_case_id') == 'TC-CART-CHECKOUT-001':",
            "            _ensure_cart_items(1)",
            "        status_code, response_text = _request(case)",
            "",
            "    with allure.step('断言结果：校验响应状态码符合预期'):",
            "        expected_status_codes = case['expected_status_codes']",
            "        effective_status_code = _effective_status_code(status_code, response_text)",
            "        _json_attachment(",
            "            '断言结果',",
            "            {",
            "                'actual_http_status_code': status_code,",
            "                'actual_effective_status_code': effective_status_code,",
            "                'expected_status_codes': expected_status_codes,",
            "                'response_preview': response_text[:1000],",
            "            },",
            "        )",
            "        assert effective_status_code in expected_status_codes",
        ]
    )
